import React from "react";

// The react.js application.
// In index.html, the <div class="root"></root> is the section modified by this code.
// The code is responsible for getting activity data from scrape/games.csv and generating corresponding HTML.
class App extends React.Component {

    constructor(props) {
        super(props);
        // Update activities with parseActivities() from CSV file generated by game_scrape.py.
        this.activities = <div class="activity">Activity A</div>;
    }

    // Render ALL activities. Called by index.js and inserted into index.html.
    render() {
        return (
          this.activities
        );
    }
}


export default App;
