import React from "react";

// The react.js application.
// In index.html, the <div class="root"></root> is the section modified by this code.
// The code is responsible for getting activity data from scrape/games.csv and generating corresponding HTML.
class App extends React.Component {

    constructor(props) {
        super(props);
        this.state = {
            tableData: [
                {name: 'John', age: 25},
                {name: 'Peter', age: 43}
            ]
        };
        // Update activities with parseActivities() from CSV file generated by game_scrape.py.
        this.activities = null;
        this.parseActivities().then(r => this.activities);
    }

    // Generate HTML for all activities.
    async parseActivities()  {
        const csv = require('csv-parser');
        let fs = require('fs');
        const results = [];
        const stream = fs.createReadStream('scrape/games.csv');
        stream.pipe(csv());
        stream.on('data', (data) => results.push(
            <div class="activity">{data}</div>
        ));
        stream.on('end', () => {
            console.log(results);
        });
    }

    // Render ALL activities. Called by index.js and inserted into index.html.
    render() {
        return (
          this.activities
        );
    }
}


export default App;
